### ISSUE TITLE
Dockerfile could not be found in the expected location.  

### ISSUE THREAD

**Issue by shiv-modi** [sanya-mahajan/rapidfort-Docx-to-PDF-#1]
Hii Sanya,

There is an error in your file : 

### Description  
The GitHub Actions workflow failed with the following error:  

This error occurs because the Dockerfile could not be found in the expected location.  

### Solution  
Update the workflow file `.github/workflows/docker-build.yml` to specify the correct path to the Dockerfile. Below is the corrected configuration:  

```yaml
name: Docker Build  

on:  
  push:  
    branches:  
      - main  

jobs:  
  build:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout code  
        uses: actions/checkout@v3  

      - name: Build Docker image  
        run: docker build -t doc-to-pdf-app -f doc_to_pdf/Dockerfile .
```

## Additional Note

You have made a naming mistake by writing `docx-to-pdf` as `doc_to_pdf`.
